# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.8'
          cache: true

      - name: Check out code
        uses: actions/checkout@v4

      - name: Install UPX
        run: |
          sudo apt-get update
          sudo apt-get install -y upx

      - name: Make build script executable
        run: chmod +x build.sh

      - name: Run build script
        run: ./build.sh

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: bluelink-binaries
          path: build/
          retention-days: 5

      - name: Test
        run: go test -v ./...

      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage.txt
          retention-days: 5
